-- DROP SCHEMA IF EXISTS `pratica_form_test` ;
-- CREATE DATABASE pratica_form_test;
--
-- use pratica_form_test;
--
-- CREATE TABLE users (
-- 	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- 	name VARCHAR(100) NOT NULL,
-- 	sex INT(1) NOT NULL,
-- 	email VARCHAR(50) NOT NULL,
-- 	type_doc VARCHAR(3) NOT NULL,
-- 	doc VARCHAR(50),
-- 	date TIMESTAMP
-- );
-- MySQL Script generated by MySQL Workbench
-- Wed Dec 26 15:36:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pratica_formulario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pratica_formulario` ;

-- -----------------------------------------------------
-- Schema pratica_formulario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pratica_formulario` DEFAULT CHARACTER SET utf8 ;
USE `pratica_formulario` ;

-- -----------------------------------------------------
-- Table `pratica_formulario`.`sexos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`sexos` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`sexos` (
  `id` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sexos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pessoas_sexos1`
    FOREIGN KEY (`sexos_id`)
    REFERENCES `pratica_formulario`.`sexos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`documentos` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_id` INT NOT NULL,
  `documento` VARCHAR(45) NULL,
  `tipo_documento_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_documentos_tipo_documento`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `pratica_formulario`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `pratica_formulario`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`estados` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`cidades` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cidades_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `pratica_formulario`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`enderecos` (
  `id` INT NOT NULL,
  `logradouro` VARCHAR(200) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(200) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_endereco_cidades1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `pratica_formulario`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_pessoas1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `pratica_formulario`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`telefones` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`telefones` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ddd` VARCHAR(2) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `pessoas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_telefones_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `pratica_formulario`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratica_formulario`.`tipo_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pratica_formulario`.`tipo_telefone` ;

CREATE TABLE IF NOT EXISTS `pratica_formulario`.`tipo_telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `telefone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tipo_telefone_telefone1`
    FOREIGN KEY (`telefone_id`)
    REFERENCES `pratica_formulario`.`telefones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
